services:
  ear-training:
    build: .
    container_name: ear-training
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data

    networks:
      - caddy_default

networks:
  caddy_default:
    external: true
